/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videorental.Views;

/**
 *
 * @author Ibrahim-Abdullah
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddMovie = new javax.swing.JButton();
        btnViewMovie = new javax.swing.JButton();
        btnSearchMovie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MovieMenu = new javax.swing.JMenu();
        jMenuItemAddMovie = new javax.swing.JMenuItem();
        jMenuItemEditMovie = new javax.swing.JMenuItem();
        jMenuItemDeleteMovie = new javax.swing.JMenuItem();
        SearchMenu = new javax.swing.JMenu();
        jMenuItemSearchMovie = new javax.swing.JMenuItem();
        ViewMenu = new javax.swing.JMenu();
        jMenuItemViewCollection = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Collection");
        setName("Menu"); // NOI18N

        btnAddMovie.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAddMovie.setText("Add Movie ");
        btnAddMovie.setRequestFocusEnabled(false);

        btnViewMovie.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnViewMovie.setText("View Movie ");
        btnViewMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMovieActionPerformed(evt);
            }
        });

        btnSearchMovie.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnSearchMovie.setText("Search Movie");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("MOVIE COLLECTION ");

        btnExit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        MovieMenu.setMnemonic('M');
        MovieMenu.setText("Movie");
        MovieMenu.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N

        jMenuItemAddMovie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAddMovie.setMnemonic('A');
        jMenuItemAddMovie.setText("Add Movie");
        MovieMenu.add(jMenuItemAddMovie);

        jMenuItemEditMovie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditMovie.setMnemonic('E');
        jMenuItemEditMovie.setText("Edit Movie");
        MovieMenu.add(jMenuItemEditMovie);

        jMenuItemDeleteMovie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDeleteMovie.setMnemonic('D');
        jMenuItemDeleteMovie.setText("Delete Movie ");
        jMenuItemDeleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteMovieActionPerformed(evt);
            }
        });
        MovieMenu.add(jMenuItemDeleteMovie);

        jMenuBar1.add(MovieMenu);

        SearchMenu.setMnemonic('S');
        SearchMenu.setText("Search");
        SearchMenu.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N

        jMenuItemSearchMovie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSearchMovie.setMnemonic('S');
        jMenuItemSearchMovie.setText("Search Movie");
        SearchMenu.add(jMenuItemSearchMovie);

        jMenuBar1.add(SearchMenu);

        ViewMenu.setMnemonic('V');
        ViewMenu.setText("View");
        ViewMenu.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N

        jMenuItemViewCollection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemViewCollection.setMnemonic('V');
        jMenuItemViewCollection.setText("View Collection");
        ViewMenu.add(jMenuItemViewCollection);

        jMenuBar1.add(ViewMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAddMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchMovie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMovieActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void jMenuItemDeleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeleteMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MovieMenu;
    private javax.swing.JMenu SearchMenu;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.JButton btnAddMovie;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearchMovie;
    private javax.swing.JButton btnViewMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAddMovie;
    private javax.swing.JMenuItem jMenuItemDeleteMovie;
    private javax.swing.JMenuItem jMenuItemEditMovie;
    private javax.swing.JMenuItem jMenuItemSearchMovie;
    private javax.swing.JMenuItem jMenuItemViewCollection;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the MovieMenu
     */
    public javax.swing.JMenu getMovieMenu() {
        return MovieMenu;
    }

    /**
     * @param MovieMenu the MovieMenu to set
     */
    public void setMovieMenu(javax.swing.JMenu MovieMenu) {
        this.MovieMenu = MovieMenu;
    }

    /**
     * @return the btnAddMovie
     */
    public javax.swing.JButton getBtnAddMovie() {
        return btnAddMovie;
    }

    /**
     * @param btnAddMovie the btnAddMovie to set
     */
    public void setBtnAddMovie(javax.swing.JButton btnAddMovie) {
        this.btnAddMovie = btnAddMovie;
    }

    /**
     * @return the btnExit
     */
    public javax.swing.JButton getBtnExit() {
        return btnExit;
    }

    /**
     * @param btnExit the btnExit to set
     */
    public void setBtnExit(javax.swing.JButton btnExit) {
        this.btnExit = btnExit;
    }

    /**
     * @return the btnSearchMovie
     */
    public javax.swing.JButton getBtnSearchMovie() {
        return btnSearchMovie;
    }

    /**
     * @param btnSearchMovie the btnSearchMovie to set
     */
    public void setBtnSearchMovie(javax.swing.JButton btnSearchMovie) {
        this.btnSearchMovie = btnSearchMovie;
    }

    /**
     * @return the btnViewMovie
     */
    public javax.swing.JButton getBtnViewMovie() {
        return btnViewMovie;
    }

    /**
     * @param btnViewMovie the btnViewMovie to set
     */
    public void setBtnViewMovie(javax.swing.JButton btnViewMovie) {
        this.btnViewMovie = btnViewMovie;
    }

    /**
     * @return the jMenuItemAddMovie
     */
    public javax.swing.JMenuItem getjMenuItemAddMovie() {
        return jMenuItemAddMovie;
    }

    /**
     * @param jMenuItemAddMovie the jMenuItemAddMovie to set
     */
    public void setjMenuItemAddMovie(javax.swing.JMenuItem jMenuItemAddMovie) {
        this.jMenuItemAddMovie = jMenuItemAddMovie;
    }

    /**
     * @return the jMenuItemDeleteMovie
     */
    public javax.swing.JMenuItem getjMenuItemDeleteMovie() {
        return jMenuItemDeleteMovie;
    }

    /**
     * @param jMenuItemDeleteMovie the jMenuItemDeleteMovie to set
     */
    public void setjMenuItemDeleteMovie(javax.swing.JMenuItem jMenuItemDeleteMovie) {
        this.jMenuItemDeleteMovie = jMenuItemDeleteMovie;
    }

    /**
     * @return the jMenuItemEditMovie
     */
    public javax.swing.JMenuItem getjMenuItemEditMovie() {
        return jMenuItemEditMovie;
    }

    /**
     * @param jMenuItemEditMovie the jMenuItemEditMovie to set
     */
    public void setjMenuItemEditMovie(javax.swing.JMenuItem jMenuItemEditMovie) {
        this.jMenuItemEditMovie = jMenuItemEditMovie;
    }

    /**
     * @return the SearchMenu
     */
    public javax.swing.JMenu getSearchMenu() {
        return SearchMenu;
    }

    /**
     * @return the ViewMenu
     */
    public javax.swing.JMenu getViewMenu() {
        return ViewMenu;
    }

    /**
     * @return the jMenuItemViewCollection
     */
    public javax.swing.JMenuItem getjMenuItemViewCollection() {
        return jMenuItemViewCollection;
    }

    /**
     * @return the jMenuItemSearchMovie
     */
    public javax.swing.JMenuItem getjMenuItemSearchMovie() {
        return jMenuItemSearchMovie;
    }
}
